FROM storm-base

RUN  apt-get update && apt-get install python3 
EXPOSE 6700

COPY worker-start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

ENTRYPOINT [ "/usr/local/bin/start.sh" ]