FROM storm-base

RUN  apt-get update && apt-get install python3 

EXPOSE 8081

COPY ui-start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

ENTRYPOINT [ "/usr/local/bin/start.sh" ]

